//
// Created by Christopher Scherban on 1/14/18.
//

#include "InvalidSearchException.h"
#include<iostream>

InvalidSearchException::InvalidSearchException(const char *message) : runtime_error(""){
    msg =  message;
    querry =  "Not available";

}
InvalidSearchException::InvalidSearchException(const char *message,const char *q) : runtime_error(""){
    msg = message;
    querry = q;

}

const char* InvalidSearchException::getMessage() {
    return msg;
}
const char* InvalidSearchException::getQuerry() {
    return querry;
}
const char *InvalidSearchException::what() const throw(){
    std::string returnVal = msg;
    returnVal += "\nThis problem was generated by the following search Parameter: ";
    returnVal += querry;
    return returnVal.c_str();
}
